apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-xqchhoat
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-xqchhoat:ee9f8f0f57a829839232ace480e78325ffba17a7@sha256:ff597e521b4feea414ea90ba6c357cdcccc31f7b671386d40803d8cd50746b79
          name: container-image
